name: Flake8 Lint Check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest  # Use latest Ubuntu as runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clone the repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use Python 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8  # Install Flake8

      - name: Run Flake8
        run: flake8 .  # Run Flake8 on the entire repo
